;; Research input, not a proposed application package or stable ABI.
(module
  (import "note4_probe" "emit" (func $emit (param i32 i32) (result i32)))
  (memory (export "memory") 1 1)
  (data (i32.const 0) "NOTE4")
  (func (export "step") (result i32)
    (local $i i32) (local $sum i32)
    (loop $next
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (local.set $sum (i32.add (local.get $sum) (local.get $i)))
      (br_if $next (i32.lt_u (local.get $i) (i32.const 64))))
    (drop (call $emit (i32.const 0) (i32.const 5)))
    (local.get $sum))
  (func (export "out_of_bounds") (result i32)
    (i32.load (i32.const 65536)))
  (func (export "bad_import") (result i32)
    (call $emit (i32.const -4) (i32.const 8)))
  (func (export "long_import") (result i32)
    (call $emit (i32.const 0) (i32.const 128)))
  (func (export "grow") (result i32)
    (memory.grow (i32.const 1)))
  (func (export "spin") (result i32)
    (loop $forever (br $forever))
    (i32.const 0))
  (func $recurse (export "recurse") (result i32)
    (call $recurse)))
