#!/usr/bin/env python3
"""Extract only system-language glyphs from the committed OFL reader font.

Run with uv run --no-project tools/generate-ui-font.py.
The generated header is used only when Chinese UI is enabled without Reader.
"""

import ast
import re
import runpy
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent


def unpack_glyph(source, index, count):
    """Expand the reader's width bits and four shared 8x8 tiles."""
    width_bytes = (count + 7) // 8
    tile_base = width_bytes + count * 8
    if not 0 <= index < count or len(source) < tile_base or (len(source) - tile_base) % 8:
        raise ValueError("Invalid packed reader font")
    glyph = bytearray(33)
    glyph[0] = 16 if source[index // 8] & (1 << (index % 8)) else 8
    for tile in range(4):
        position = width_bytes + index * 8 + tile * 2
        offset = tile_base + int.from_bytes(source[position:position + 2], "little") * 8
        if offset + 8 > len(source):
            raise ValueError("Reader font tile outside data")
        for row in range(8):
            glyph[1 + (tile // 2 * 8 + row) * 2 + tile % 2] = source[offset + row]
    return glyph


def main():
    strings = (ROOT / "components/zectrix_app/include/zectrix_strings.inc").read_text()
    literals = re.findall(r'"(?:[^"\\]|\\.)*"', strings)
    codepoints = sorted({ord(char) for literal in literals
                         for char in ast.literal_eval(literal) if ord(char) >= 128})
    ranges = runpy.run_path(str(ROOT / "tools/generate-reader-font.py"))["RANGES"]
    count = sum(last - first + 1 for first, last in ranges)
    source = (ROOT / "components/zectrix_reader/font/reader_font.bin").read_bytes()
    glyphs = []
    for codepoint in codepoints:
        offset = 0
        for first, last in ranges:
            if first <= codepoint <= last:
                index = offset + codepoint - first
                glyphs.append(unpack_glyph(source, index, count))
                break
            offset += last - first + 1
        else:
            raise ValueError(f"Unsupported UI codepoint U+{codepoint:04X}")
    output = "// Generated by tools/generate-ui-font.py from GNU Unifont 15.1.05.\n"
    output += "// Font data: SIL OFL 1.1; see font/README.md.\n#pragma once\n\n#include <cstdint>\n\n"
    output += "constexpr uint16_t kUiChineseCodepoints[] = {\n"
    for start in range(0, len(codepoints), 12):
        output += "    " + ", ".join(f"0x{cp:04x}" for cp in codepoints[start:start + 12]) + ",\n"
    output += "};\nconstexpr uint8_t kUiChineseBitmaps[][33] = {\n"
    for cp, glyph in zip(codepoints, glyphs):
        output += "    {" + ", ".join(f"0x{byte:02x}" for byte in glyph) + f"}}, // U+{cp:04X}\n"
    output += "};\n"
    path = ROOT / "components/zectrix_demo_ui/font/zectrix_ui_chinese_font.h"
    path.write_text(output)
    print(f"UI Chinese: {len(codepoints)} glyphs, {len(codepoints) * 35} bytes including indices")


if __name__ == "__main__":
    main()
