#!/usr/bin/env python3
"""Generate compact 48px firmware numerals from artwork and editable raster parameters."""
# /// script
# requires-python = ">=3.10"
# dependencies = ["pillow>=11,<13"]
# ///
import argparse
import json
from pathlib import Path
from PIL import Image, ImageDraw
from digit_font import ROOT, source_glyphs, rasterize, trim, bits_of, choose, CODECS

def load_recipe(path):
    if path is None:
        return [("lanczos", 150)] * 50
    recipe = json.loads(path.read_text())
    if recipe.get("height") != 48 or len(recipe.get("glyphs", [])) != 50:
        raise ValueError("Expected fifty 48px glyph parameters")
    result = [None] * 50
    for entry in recipe["glyphs"]:
        style, digit = entry["style"], entry["digit"]
        method, threshold = entry["method"], entry["threshold"]
        if type(style) is not int or type(digit) is not int or not 0 <= style < 5 or not 0 <= digit < 10:
            raise ValueError("Invalid style/digit")
        if method not in ("lanczos", "area") or type(threshold) is not int or not 1 <= threshold <= 254:
            raise ValueError("Invalid raster parameters")
        index = style * 10 + digit
        if result[index] is not None:
            raise ValueError("Duplicate glyph parameters")
        result[index] = method, threshold
    if any(entry is None for entry in result):
        raise ValueError("Missing glyph parameters")
    return result

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "components/ui/font/large_digits.h")
    parser.add_argument("--preview", type=Path, default=ROOT / "docs/design/date-digits/native-48px.png")
    parser.add_argument("--recipe", type=Path, default=ROOT / "docs/design/date-digits/raster-settings.json")
    parser.add_argument("--original-raster", action="store_true", help="Use original Lanczos/150 raster parameters")
    parser.add_argument("--legacy-codecs", action="store_true", help="Only raw and pixel RLE for comparison")
    parser.add_argument("--codecs", nargs="+", choices=CODECS, help="Explicit streaming codec set for measurement")
    args = parser.parse_args()
    if args.legacy_codecs and args.codecs:
        parser.error("Choose --legacy-codecs or --codecs, not both")
    configured_codecs = CODECS
    if not args.original_raster and args.recipe.exists():
        configured_codecs = json.loads(args.recipe.read_text()).get("codecs", CODECS)
        if not configured_codecs or any(name not in CODECS for name in configured_codecs):
            raise ValueError("Invalid configured codecs")
    codecs = (0, 1) if args.legacy_codecs else tuple(CODECS.index(name) for name in (args.codecs or configured_codecs))
    recipe = load_recipe(None if args.original_raster else args.recipe)
    sources = source_glyphs()
    blob, metadata, raw_total, legacy_total = bytearray(), [], 0, 0
    sheet = Image.new("1", (500, 420), 1)
    draw = ImageDraw.Draw(sheet)
    counts = [0, 0, 0, 0]
    for index, (source, (method, threshold)) in enumerate(zip(sources, recipe)):
        glyph = trim(rasterize(source, 48, threshold, method))
        bits = bits_of(glyph)
        payload, codec, raw_size = choose(bits, glyph.width, codecs)
        legacy_total += len(choose(bits, glyph.width, (0, 1))[0])
        metadata.append((len(blob), len(payload), glyph.width, codec))
        blob.extend(payload)
        raw_total += raw_size
        counts[codec] += 1
        style, digit = divmod(index, 10)
        sheet.paste(glyph, (digit * 50 + (50 - glyph.width) // 2, style * 84 + 18))
        if digit == 0:
            draw.text((4, style * 84 + 2), "ABCDE"[style], fill=0)
    if len(blob) > 65535:
        raise ValueError("Glyph data exceeds uint16 offsets")
    lines = ["// Generated by tools/generate-large-digits.py; source: docs/design/date-digits/*.png.",
             "// Editable raster parameters: docs/design/date-digits/raster-settings.json.",
             "// 48px native 1bpp; codecs: 0=raw, 1=row runs, 2=row-XOR runs, 3=column runs.",
             "#pragma once", "#include <cstdint>",
             f"inline constexpr bool kNote4DigitUsesXor = {'true' if counts[2] else 'false'};",
             f"inline constexpr bool kNote4DigitUsesColumn = {'true' if counts[3] else 'false'};",
             "struct Note4DigitGlyph { uint16_t offset, size; uint8_t width, codec; };",
             "inline constexpr Note4DigitGlyph kNote4DigitGlyphs[50] = {"]
    lines.extend("    {%d, %d, %d, %d}," % record for record in metadata)
    lines.extend(["};", "inline constexpr uint8_t kNote4DigitData[] = {"])
    lines.extend("    " + ", ".join(f"0x{v:02x}" for v in blob[i:i + 24]) + "," for i in range(0, len(blob), 24))
    lines.extend(["};", ""])
    args.output.write_text("\n".join(lines), encoding="utf-8")
    sheet.save(args.preview)
    print(f"Raw={raw_total}, legacy selected payload={legacy_total}, new payload={len(blob)}, index=300, total={len(blob)+300} bytes")
    print(f"Glyph codecs: {dict(zip(CODECS, counts))}")

if __name__ == "__main__":
    main()
