#!/usr/bin/env python3
"""Extract only system-language glyphs from the committed OFL reader font.

Run with uv run --no-project tools/generate-ui-font.py.
The generated header is used only when Chinese UI is enabled without Reader.
"""

import ast
import re
import runpy
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent


def main():
    strings = (ROOT / "components/zectrix_app/include/zectrix_strings.inc").read_text()
    literals = re.findall(r'"(?:[^"\\]|\\.)*"', strings)
    codepoints = sorted({ord(char) for literal in literals
                         for char in ast.literal_eval(literal) if ord(char) >= 128})
    ranges = runpy.run_path(str(ROOT / "tools/generate-reader-font.py"))["RANGES"]
    source = (ROOT / "components/zectrix_reader/font/reader_font.bin").read_bytes()
    glyphs = []
    for codepoint in codepoints:
        offset = 0
        for first, last in ranges:
            if first <= codepoint <= last:
                index = offset + codepoint - first
                glyphs.append(source[index * 33:(index + 1) * 33])
                break
            offset += last - first + 1
        else:
            raise ValueError(f"Unsupported UI codepoint U+{codepoint:04X}")
    output = "// Generated by tools/generate-ui-font.py from GNU Unifont 15.1.05.\n"
    output += "// Font data: SIL OFL 1.1; see font/README.md.\n#pragma once\n\n#include <cstdint>\n\n"
    output += "constexpr uint16_t kUiChineseCodepoints[] = {\n"
    for start in range(0, len(codepoints), 12):
        output += "    " + ", ".join(f"0x{cp:04x}" for cp in codepoints[start:start + 12]) + ",\n"
    output += "};\nconstexpr uint8_t kUiChineseBitmaps[][33] = {\n"
    for cp, glyph in zip(codepoints, glyphs):
        output += "    {" + ", ".join(f"0x{byte:02x}" for byte in glyph) + f"}}, // U+{cp:04X}\n"
    output += "};\n"
    path = ROOT / "components/zectrix_demo_ui/font/zectrix_ui_chinese_font.h"
    path.write_text(output)
    print(f"UI Chinese: {len(codepoints)} glyphs, {len(codepoints) * 35} bytes including indices")


if __name__ == "__main__":
    main()
