#!/usr/bin/env python3
# /// script
# dependencies = ["pillow==11.3.0", "numpy>=2,<3", "scipy>=1.14,<2"]
# ///
"""Rasterize a bounded UI subset of Noto Sans CJK SC 2.004 at native sizes.

uv run tools/generate-editorial-font.py --source build-font-sources
Source OTFs remain outside the firmware/repository; committed 1bpp glyphs are
packed without scanline padding. Unknown names retain the existing reader fallback.
"""
import argparse
import ast
import math
import re
import json
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import numpy as np
from scipy import ndimage as ndi

ROOT = Path(__file__).resolve().parent.parent

def raster(font, cp, width, height, baseline, scale=1):
    image = Image.new("L", (width * scale, height * scale), 0)
    ImageDraw.Draw(image).text((0, baseline * scale), chr(cp), font=font,
                              fill=255, anchor="ls")
    return np.asarray(image.resize((width, height), Image.Resampling.BOX), dtype=float) / 255

def topology(mask):
    # Four-connected strokes and eight-connected background avoid diagonal ambiguity.
    foreground = ndi.label(mask)[1]
    background = ndi.label(~np.pad(mask, 1), np.ones((3, 3)))[1] - 1
    return foreground, background

def quality(mask, coverage, reference):
    if not reference.any():
        return float(mask.sum())
    a, b = mask & ~ndi.binary_erosion(mask), reference & ~ndi.binary_erosion(reference)
    if not a.any():
        return 1000.0
    distances = np.concatenate((ndi.distance_transform_edt(~a)[b],
                                ndi.distance_transform_edt(~b)[a]))
    roi = ndi.binary_dilation(reference, iterations=1)
    # Explicit engineering proxy, not measured human readability or panel physics.
    return (float(np.percentile(distances, 95)) +
            float(np.mean((mask.astype(float)[roi] - coverage[roi]) ** 2)) +
            abs(int(mask.sum()) - int(reference.sum())) / max(1, int(reference.sum())))

def pack(mask):
    rows = np.flatnonzero(mask.any(axis=1))
    top, bottom = (int(rows[0]), int(rows[-1]) + 1) if rows.size else (0, 0)
    return np.packbits(mask[top:bottom].reshape(-1)).tobytes(), top, bottom - top

def pareto(rows):
    return [r for r in rows if not any(
        q["bytes"] <= r["bytes"] and q["distortion"] <= r["distortion"] and
        (q["bytes"] < r["bytes"] or q["distortion"] < r["distortion"])
        for q in rows)]

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--report", type=Path)
    args = parser.parse_args()
    literals = re.findall(r'"(?:[^"\\]|\\.)*"',
                         (ROOT / "components/note4_app/include/note4_strings.inc").read_text())
    chars = set("".join(ast.literal_eval(item) for item in literals))
    chars.update(chr(cp) for cp in range(32, 127))
    chars.update("风从海上来…")
    codepoints = sorted(ord(char) for char in chars if ord(char) >= 32)
    output = ["// Generated by tools/generate-editorial-font.py; Noto Sans CJK SC 2.004.",
              "// SIL OFL 1.1: see font/OFL-NotoSansCJK.txt and font/README.md.",
              "#pragma once", "#include <cstdint>",
              "struct EditorialGlyph { uint32_t codepoint, offset; uint8_t width, top, rows; };", ""]
    total = 0
    report = {"model": "uncalibrated geometric/coverage proxy; no physical power or readability claims",
              "selection": "per-face Pareto frontier, minimum distortion then bytes; native fallback on topology regression",
              "faces": []}
    for name, size, weight in [("Caption", 14, "Regular"), ("Navigation", 18, "Regular"),
                               ("Selected", 18, "Bold"), ("Heading", 22, "Bold"),
                               ("Compact", 16, "Bold"), ("Label", 16, "Regular"),
                               ("Micro", 12, "Regular")]:
        font = ImageFont.truetype(str(args.source / f"NotoSansCJKsc-{weight}.otf"), size)
        data, records = [], []
        height = size + (6 if size == 22 else 4)
        baseline = size if size == 12 else size - 1
        fonts = {scale: ImageFont.truetype(str(args.source / f"NotoSansCJKsc-{weight}.otf"), size * scale)
                 for scale in (1, 2, 4)}
        glyphs = []
        candidates = {(scale, threshold): [] for scale in (1, 2, 4) for threshold in (112, 128, 144)}
        original_bytes = 0
        for cp in (range(32, 127) if name == "Micro" else codepoints):
            width = max(1, math.ceil(font.getlength(chr(cp))))
            bounds = font.getbbox(chr(cp), anchor="ls")
            if baseline + bounds[1] < 0 or baseline + bounds[3] > height:
                raise ValueError(f"Clipped glyph U+{cp:04X} in {name}")
            coverage = {scale: raster(fonts[scale], cp, width, height, baseline, scale) for scale in fonts}
            native = coverage[1] >= 128 / 255
            reference = coverage[4] >= 128 / 255
            ref_topology = topology(reference)
            native_error = sum(abs(a - b) for a, b in zip(topology(native), ref_topology))
            glyphs.append((cp, width))
            original_bytes += (width * height + 7) // 8
            for (scale, threshold), masks in candidates.items():
                mask = coverage[scale] >= threshold / 255
                error = sum(abs(a - b) for a, b in zip(topology(mask), ref_topology))
                # Never introduce additional disconnected strokes/lost holes vs native.
                fallback = error > native_error
                if fallback: mask = native
                packed, top, rows = pack(mask)
                masks.append((packed, top, rows, quality(mask, coverage[4], reference), fallback))
        scores = [{"scale": scale, "threshold": threshold,
                   "bytes": sum(len(m[0]) for m in masks),
                   "distortion": sum(m[3] for m in masks) / len(masks),
                   "fallbacks": sum(m[4] for m in masks)}
                  for (scale, threshold), masks in candidates.items()]
        frontier = pareto(scores)
        chosen = min(frontier, key=lambda r: (r["distortion"], r["bytes"], r["scale"], r["threshold"]))
        for (cp, width), (packed, top, rows, _, _) in zip(glyphs, candidates[chosen["scale"], chosen["threshold"]]):
            records.append((cp, len(data), width, top, rows))
            data.extend(packed)
        report["faces"].append({"name": name, "original_bitmap_bytes": original_bytes,
                                "selected": chosen, "pareto": frontier, "candidates": scores})
        output.append(f"constexpr int kEditorial{name}Height = {height};")
        output.append(f"constexpr int kEditorial{name}Size = {size};")
        output.append(f"constexpr EditorialGlyph kEditorial{name}Glyphs[] = {{")
        output.extend(f"    {{0x{cp:x}, {offset}, {width}, {top}, {rows}}}," for cp, offset, width, top, rows in records)
        output.append("};")
        output.append(f"constexpr uint8_t kEditorial{name}Data[] = {{")
        output.extend("    " + ",".join(str(byte) for byte in data[start:start+32]) + ","
                      for start in range(0, len(data), 32))
        output.extend(["};", ""])
        total += len(data) + len(records) * 12
    (ROOT / "components/ui/font/editorial_font.h").write_text("\n".join(output))
    report["total_glyph_and_index_bytes"] = total
    destination = args.report or args.source / "editorial-optimization.json"
    destination.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n")
    print(f"Editorial subset: {len(codepoints)} glyphs × 6 faces + 95 ASCII micro glyphs; {total:,} bytes")

if __name__ == "__main__":
    main()
