#pragma once

// Host tests default to the full product. Individual tests can override a
// module with -DCONFIG_ZECTRIX_ENABLE_*=0 before compiling production sources.
#ifndef CONFIG_ZECTRIX_ENABLE_CONNECTIVITY
#define CONFIG_ZECTRIX_ENABLE_CONNECTIVITY 1
#endif
#ifndef CONFIG_ZECTRIX_ENABLE_WIFI
#define CONFIG_ZECTRIX_ENABLE_WIFI CONFIG_ZECTRIX_ENABLE_CONNECTIVITY
#endif
#ifndef CONFIG_ZECTRIX_ENABLE_WIFI_HTTP
#define CONFIG_ZECTRIX_ENABLE_WIFI_HTTP CONFIG_ZECTRIX_ENABLE_WIFI
#endif
#ifndef CONFIG_ZECTRIX_ENABLE_BOOK_TRANSFER
#define CONFIG_ZECTRIX_ENABLE_BOOK_TRANSFER CONFIG_ZECTRIX_ENABLE_WIFI
#endif
#ifndef CONFIG_ZECTRIX_ENABLE_READER
#define CONFIG_ZECTRIX_ENABLE_READER 1
#endif
#ifndef CONFIG_ZECTRIX_ENABLE_USB_CLI
#define CONFIG_ZECTRIX_ENABLE_USB_CLI 1
#endif
#ifndef CONFIG_ZECTRIX_ENABLE_UPDATE
#define CONFIG_ZECTRIX_ENABLE_UPDATE 1
#endif
#ifndef CONFIG_ZECTRIX_ENABLE_BOOK_STORAGE
#define CONFIG_ZECTRIX_ENABLE_BOOK_STORAGE (CONFIG_ZECTRIX_ENABLE_READER || CONFIG_ZECTRIX_ENABLE_BOOK_TRANSFER)
#endif
