#pragma once

#ifndef CONFIG_NOTE4_ENABLE_UI_CHINESE
#define CONFIG_NOTE4_ENABLE_UI_CHINESE 1
#endif
// Existing image fixtures run in English; localization tests select both.
#ifndef CONFIG_NOTE4_UI_DEFAULT_CHINESE
#define CONFIG_NOTE4_UI_DEFAULT_CHINESE 0
#endif

// Host tests default to the full product. Individual tests can override a
// module with -DCONFIG_NOTE4_ENABLE_*=0 before compiling production sources.
#ifndef CONFIG_NOTE4_ENABLE_CONNECTIVITY
#define CONFIG_NOTE4_ENABLE_CONNECTIVITY 1
#endif
#ifndef CONFIG_NOTE4_ENABLE_WIFI
#define CONFIG_NOTE4_ENABLE_WIFI CONFIG_NOTE4_ENABLE_CONNECTIVITY
#endif
#ifndef CONFIG_NOTE4_ENABLE_WIFI_HTTP
#define CONFIG_NOTE4_ENABLE_WIFI_HTTP CONFIG_NOTE4_ENABLE_WIFI
#endif
#ifndef CONFIG_NOTE4_ENABLE_BOOK_TRANSFER
#define CONFIG_NOTE4_ENABLE_BOOK_TRANSFER CONFIG_NOTE4_ENABLE_WIFI
#endif
#ifndef CONFIG_NOTE4_ENABLE_READER
#define CONFIG_NOTE4_ENABLE_READER 1
#endif
#ifndef CONFIG_NOTE4_ENABLE_RUNTIME
#define CONFIG_NOTE4_ENABLE_RUNTIME 1
#endif
#ifndef CONFIG_NOTE4_ENABLE_UTILITIES
#define CONFIG_NOTE4_ENABLE_UTILITIES 1
#endif
#ifndef CONFIG_NOTE4_ENABLE_USB_CLI
#define CONFIG_NOTE4_ENABLE_USB_CLI 1
#endif
#ifndef CONFIG_NOTE4_ENABLE_USB_HOST
#define CONFIG_NOTE4_ENABLE_USB_HOST CONFIG_NOTE4_ENABLE_USB_CLI
#endif
#ifndef CONFIG_NOTE4_ENABLE_UPDATE
#define CONFIG_NOTE4_ENABLE_UPDATE 1
#endif
#ifndef CONFIG_NOTE4_ENABLE_BOOK_STORAGE
#define CONFIG_NOTE4_ENABLE_BOOK_STORAGE (CONFIG_NOTE4_ENABLE_READER || CONFIG_NOTE4_ENABLE_BOOK_TRANSFER || CONFIG_NOTE4_ENABLE_USB_HOST || CONFIG_NOTE4_ENABLE_RUNTIME)
#endif
